version: 2.1
orbs:
  github-release: h-matsuo/github-release@0.1.3
jobs:
  build:
    docker:
      - image: circleci/rust:stretch
    environment:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Dependencies
          command: |
              sudo sh -c 'echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list'
              sudo apt-get update
              sudo apt-get clean
              sudo rm -r /var/lib/apt/lists/*
              rustup component add clippy rustfmt
      - run:
          name: Build
          command: ci/script.sh
  deploy:
    description: Create dummy file and publish a new release tagged `vX.Y.Z`.
    environment:
      TARGET: x86_64-unknown-linux-gnu
      CIRCLECI_TEST: true
    executor: github-release/default
    steps:
      - run:
          command: |
            mkdir artifacts
            echo dummy > ./artifacts/file
      # - github-release/create:
      #     tag: v1.2.3
      #     title: Version v1.2.3
      #     description: This release is version v1.2.3
      #     file-path: ./artifacts/file
      - run:
          command: go get github.com/aktau/github-release github.com/tcnksm/ghr
      - run:
          command: grh --token $GITHUB_TOKEN --username $CIRCLE_PROJECT_USERNAME --repository $CIRCLE_PROJECT_REPONAME --commitish $CIRCLE_SHA1 -delete v0.0.17 ./artifacts/file
  mytest:
    docker:
      - image: circleci/rust:stretch
    environment:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - checkout
      - run:
          name: Show the Results
          command: |
              cargo run
              cat /home/circleci/circleci_temp.txt

workflows:
  version: 2.1
  build-n-deploy:
      jobs:
        - build:
            filters:  # required since `deploy` has tag filters AND requires `build`
              tags:
                only: /.*/
        - deploy:
            requires:
              - build
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
  # build-n-test:
  #     jobs:
  #       - build
  #       - mytest:
  #           requires:
  #             - build
