version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/rust:stretch

jobs:
  build:
    executor: my-executor
    environment:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Dependencies
          command: |
              sudo sh -c 'echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list'
              sudo apt-get update
              sudo apt-get clean
              sudo rm -r /var/lib/apt/lists/*
              rustup component add clippy rustfmt
      - run:
          name: Build
          command: ci/script.sh

      - run:
          name: Copy Stuff
          command: |
            mkdir -p res_dir
            cp target/debug/circleci res_dir/
            cp /home/circleci/circleci_temp.txt res_dir/

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  mytest:
    executor: my-executor
    environment:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      # - checkout
      - attach_workspace:
          at: /home/circleci
      - run: ci/run_tests.sh
      - run: cargo run
      # - run:
      #     name: Show the Results
      #     command: |
      #         cargo run
      #         cat /home/circleci/circleci_temp.txt

  deploy:
    description: Create dummy file and publish a new release tagged `vX.Y.Z`.
    docker:
      - image: circleci/golang:1.13
    environment:
      TARGET: x86_64-unknown-linux-gnu
      CIRCLECI_TEST: true
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          command: |
            go get github.com/tcnksm/ghr
            export VERSION=${CIRCLE_TAG}
            [ -n ${GITHUB_TOKEN} ] && echo "I have it!"
            [ -z ${GITHUB_TOKEN} ] && echo "I DO NOT have it!"
            [ -f target/debug/circleci ] && echo "at project" && export artifacts=target/debug/circleci
            [ -f project/target/debug/circleci ] && echo "at circleci" && export artifacts=project/target/debug/circleci
            echo ${CIRCLE_PROJECT_USERNAME} ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_SHA1} ${VERSION} ${artifacts}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ${artifacts}
          # command: grh --token $GITHUB_TOKEN --username $CIRCLE_PROJECT_USERNAME --repository $CIRCLE_PROJECT_REPONAME --commitish $CIRCLE_SHA1 -delete v0.0.17 ./artifacts/file
workflows:
  version: 2.1
  build-n-deploy:
      jobs:
        - build:
            filters:  # required since `deploy` has tag filters AND requires `build`
              tags:
                only: /.*/
        - mytest:
            requires:
              - build
            filters:
              tags:
                ignore: /^v.*/
        - deploy:
            requires:
              - build
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
  # build-n-test:
  #     jobs:
  #       - build
  #       - mytest:
  #           requires:
  #             - build
